---
agof:
  extraPlaybookOpts: '-vvv'

  agof_repo: https://github.com/mhjacks/agof.git
  agof_revision: optionalize_secrets

  iac_repo: https://github.com/validatedpatterns-demos/ansible-edge-gitops-hmi-config-as-code.git
  iac_revision: main
