---
global:
  pattern: ansible-edge-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  hub:
    provider: aws

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/mhjacks/clustergroup-chart
    clusterGroupChartGitRevision: add_extra_objects
    #clusterGroupChartVersion: 0.9.*
